import { Inject, Injectable, Logger } from "@nestjs/common";
import { Api, AuthorDto, EntityModelTeiDiv, SharedConfigDto } from "../biblioteca.api";
import { AppConfService, PROVIDER_CONF, SharedTextbaseConfig } from "../configuration";
import { assert } from "console";
import { StopWatch } from "../util";

/**
 * wrapper over the api generated by swagger-typescript-api
 */
@Injectable()
export class BibliotecaClient {
    protected tb: Api<string>;

    private readonly log = new Logger(BibliotecaClient.name);

    constructor(@Inject(PROVIDER_CONF) protected conf: AppConfService) {
        this.log.log(`will connect to biblioteca url: ${conf.bibliotecaUrl}`)
        this.tb = new Api({
            baseUrl:  conf.bibliotecaUrl,
            baseApiParams: {
              headers: {
                Accept: 'application/json',
              }
            }
          });
    }

    async getAuthors() : Promise<AuthorDto[]> {
        const resp = await this.tb.api.getAuthors();
        const authors = (resp).data;
        return authors;
    }

    async getOperaForAuthor(strId: string) {
        const opera = await this.tb.api.getOpera(strId);
        return opera.data;
    }

    async getAllOpera(pageNr = 0, pageSize = 20) {
      const watch = new StopWatch();
      // executeSearchTeidivGet8 is Spring Data REST's generated name for
      // findOpera - its numeric suffix shifts
      // whenever a sibling /api/drest/teiDivs/search/* endpoint is added or
      // removed elsewhere, so it has to be re-checked (grep biblioteca.api.ts
      // for `findOpera`) every time the client gets regenerated.
      const resp = await this.tb.api.executeSearchTeidivGet8({ page: pageNr, size: pageSize});
      const divs = resp.data._embedded.teiDivs;
      this.log.log(`GET ${this.conf.bibliotecaUrl}/api/drest/teiDivs/search/findOpera?page=${pageNr}&size=${pageSize} : done, got ${divs.length} opi, took ${watch}`);
      return divs;
    }

    async getElemByPath(path: string) {
      const resp = await this.tb.api.getElemByPath({ path: path});
      return resp.data;
    }

    /**
     * The non-secret shared-resource naming convention (Kafka topics, the
     * Milvus collection, which embedding model) textbase-server is the
     * source of truth for -- see its ConfigRestController.config(). Goes
     * through the generated client (this.tb.api.config()) like every other
     * call here; the generated SharedConfigDto type marks every field
     * optional (springdoc has no way to express "always present" for a
     * plain Map-turned-record), so this validates the fields the rest of
     * biblioteca-nestjs actually relies on being present and narrows to the
     * stricter SharedTextbaseConfig shape used everywhere else.
     */
    async getConfig(): Promise<SharedTextbaseConfig> {
      const resp = await this.tb.api.config();
      // The generated SharedConfigDto only knows the fields of whichever
      // server version biblioteca.api.ts was generated from - servers
      // older than the paragraph-section addition don't send it - so read
      // the response through a widened type here (until the next
      // gen-biblioteca-api.sh regeneration makes the cast redundant) and
      // fall back to the values that generation hardcoded in the filter.
      const cfg = resp.data as SharedConfigDto & { paragraph?: { minChars?: number; maxChars?: number } };
      if (!cfg.kafka?.newOpusImportedTopic || !cfg.kafka?.opusReimportedTopic || !cfg.kafka?.opusRemovedTopic) {
        throw new Error(`GET ${this.conf.bibliotecaUrl}/api/admin/config: missing kafka topic name(s): ${JSON.stringify(cfg.kafka)}`);
      }
      if (!cfg.milvus?.collection) {
        throw new Error(`GET ${this.conf.bibliotecaUrl}/api/admin/config: missing milvus collection name: ${JSON.stringify(cfg.milvus)}`);
      }
      if (!cfg.embedder?.model || cfg.embedder?.dimension == null) {
        throw new Error(`GET ${this.conf.bibliotecaUrl}/api/admin/config: missing embedder model/dimension: ${JSON.stringify(cfg.embedder)}`);
      }
      return {
        kafka: {
          newOpusImportedTopic: cfg.kafka.newOpusImportedTopic,
          opusReimportedTopic: cfg.kafka.opusReimportedTopic,
          opusRemovedTopic: cfg.kafka.opusRemovedTopic,
        },
        milvus: {
          collection: cfg.milvus.collection,
        },
        // A server older than the SharedConfigDto.Paragraph addition
        // (biblioteca-server 0.9.6) simply omits the whole section - fall
        // back to the very values that server generation hardcoded in the
        // vectorizer's filter, so running against it behaves identically
        // to how it always did.
        paragraph: {
          minChars: cfg.paragraph?.minChars ?? 20,
          maxChars: cfg.paragraph?.maxChars ?? 3000,
        },
        embedder: {
          model: cfg.embedder.model,
          dimension: cfg.embedder.dimension,
          description: cfg.embedder.description,
          ollamaModel: cfg.embedder.ollamaModel,
          host: cfg.embedder.host,
          port: cfg.embedder.port,
        },
      };
    }

    /**
     * @param pageSize  parameter to transmit to the api (page by page retrieval)
     * @param opId the id whose paragraphs we want
     * @param offset skip the first offset
     * @param limit  only keep limit from what remains
     */

    async *getParagraphs(opId: number, pageSize = 1000, offset = 0, limit = Number.POSITIVE_INFINITY ) {
      assert(pageSize > 0);

      var hasMore = true;
      var pageNr = Math.floor(offset / pageSize);

      let totalYielded = 0;

      while (hasMore) {

        // call /api/div/id/paras
        const watch = new StopWatch();
        
        const resp = await this.tb.api.getIdParas(opId, {
          page: pageNr,
          size: pageSize,
          withContent: 'true'
        });
        const paras = resp.data;
                
        this.log.log(`GET ${this.conf.bibliotecaUrl}/api/divs/${opId}/paras?page=${pageNr}&size=${pageSize}&withContent=true : done, got ${paras.length} paras, took ${watch}`);
        
        pageNr++;

        // if we got precisely the page size, maybe there's more.
        hasMore = (paras.length == pageSize);

        for (const p of paras) {

          if (totalYielded++ >= limit)
            return;

          yield p;
        }
      }        
    }

    /**
     * transforms a paged API call into a async generator
     * @param provider  the api call
     * @param pageNr    page number
     * @param pageSize  the page size
     * @param limit do not yield more than limit items
     */
    protected async *gen<T>(
      provider: (pageNr: number, pageSize: number) => Promise<Array<T>>,
      pageNr = 0, 
      pageSize = 1000, 
      limit = Number.POSITIVE_INFINITY, 
      ) :  AsyncGenerator<T, void, unknown> {
        var hasMore = true;
        let totalYielded = 0;
  
        while (hasMore) {
            
          const arr = await provider(pageNr, pageSize);
     
          pageNr++;
  
          // if we got precisely the page size, maybe there's more.
          hasMore = (arr.length == pageSize);

          for (const obj of arr) {
  
            if (totalYielded++ >= limit)
              return;
  
            yield obj;
          }
        }
    }

    allOperaGen(pageNr = 0, pageSize = 1000, limit = Number.POSITIVE_INFINITY ) {

      return this.gen<EntityModelTeiDiv>((pageNr, pageSize) => {
        return this.getAllOpera(pageNr, pageSize);
      })

  }

    /**
     * Fire-and-forget-ish, but awaited: raw fetch (not this.tb.api), since
     * neither of these two endpoints is in the generated client yet -
     * regenerating it needs a prod redeploy first (gen-biblioteca-api.sh
     * pulls from biblioteca-server's own live /api/docs). Failures are
     * only ever logged, never thrown: a stats-recording hiccup must not
     * interrupt the actual vectorizing run it is reporting on.
     */
    async recordEmbeddingBatchStat(stat: {
      batchSize: number; totalChars: number; vectorDimension: number; embedderModel: string; durationMs: number;
    }): Promise<void> {
      try {
        const res = await fetch(`${this.conf.bibliotecaUrl}/api/drest/embeddingBatchStats`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(stat),
        });
        if (!res.ok) {
          this.log.warn(`failed to record embedding batch stat: HTTP ${res.status}`);
        }
      } catch (err: any) {
        this.log.warn(`failed to record embedding batch stat: ${err.message}`);
      }
    }

    /** Same reasoning as recordEmbeddingBatchStat above - the opus-level counterpart. */
    async recordOpusVectorizingStat(stat: {
      opusId: number; totalParas: number; totalBatches: number; embedderModel: string; durationMs: number;
    }): Promise<void> {
      try {
        const res = await fetch(`${this.conf.bibliotecaUrl}/api/drest/opusVectorizingStats`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(stat),
        });
        if (!res.ok) {
          this.log.warn(`failed to record opus vectorizing stat: HTTP ${res.status}`);
        }
      } catch (err: any) {
        this.log.warn(`failed to record opus vectorizing stat: ${err.message}`);
      }
    }

    async persistEnrichment(update: { opusId: number; coverUrl?: string }): Promise<void> {
      const response = await fetch(`${this.conf.bibliotecaUrl}/api/internal/enrichment`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify(update),
      });
      if (!response.ok) throw new Error(`enrichment persistence returned HTTP ${response.status}`);
    }

}
