import { Inject, Injectable } from "@nestjs/common";
import { Api, AuthorDto } from "../textbase.api";
import { AppConfService, PROVIDER_CONF } from "../configuration";
import { assert } from "console";

/**
 * wrapper over the api generated by swagger-typescript-api
 */
@Injectable()
export class TextbaseClient {
    protected tb: Api<string>;

    constructor(@Inject(PROVIDER_CONF) protected conf: AppConfService) {
        this.tb = new Api({
            baseUrl:  conf.textbaseUrl, // 'http://textbase.scriptorium.ro',
            baseApiParams: {
              headers: {
                Accept: 'application/json',
              }
            }
          });
    }

    async getAuthors() : Promise<AuthorDto[]> {
        const resp = await this.tb.api.getAuthors();
        const authors = (resp).data;
        return authors;
    }

    async getOperaForAuthor(strId: string) {
        const opera = await this.tb.api.getOpera(strId);
        return opera.data;
    }

    async getAllOpera(pageNr = 0, pageSize = 20) {
      const resp = await this.tb.api.executeSearchTeidivGet6({ page: pageNr, size: pageSize});
      return resp.data._embedded.teiDivs;
    }

    /**
     * @param pageSize  parameter to transmit to the api (page by page retrieval)
     * @param opId the id whose paragraphs we want
     * @param offset skip the first offset
     * @param limit  only keep limit from what remains
     */

    async *getParagraphs(opId: number, pageSize = 2000, offset = 0, limit = Number.POSITIVE_INFINITY ) {
      assert(pageSize > 0);

      var hasMore = true;
      var pageNr = Math.floor(offset / pageSize);

      let totalYielded = 0;

      while (hasMore) {

        // call /api/div/id/paras
        const resp = await this.tb.api.getIdParas(opId, {
          page: pageNr++,
          size: pageSize,
          withContent: 'true'
        });

        const paras = resp.data

        // if we got precisely the page size, maybe there's more.
        hasMore = (paras.length == pageSize);

        for (const p of paras) {

          if (totalYielded++ >= limit)
            return;

          yield p;
        }
      }        
    }
}