import { Inject, Injectable, Logger } from "@nestjs/common";
import { Api, AuthorDto, EntityModelTeiDiv } from "../textbase.api";
import { AppConfService, PROVIDER_CONF, SharedTextbaseConfig } from "../configuration";
import { assert } from "console";
import { StopWatch } from "../util";

/**
 * wrapper over the api generated by swagger-typescript-api
 */
@Injectable()
export class TextbaseClient {
    protected tb: Api<string>;

    private readonly log = new Logger(TextbaseClient.name);

    constructor(@Inject(PROVIDER_CONF) protected conf: AppConfService) {
        this.log.log(`will connect to textbase url: ${conf.textbaseUrl}`)
        this.tb = new Api({
            baseUrl:  conf.textbaseUrl,
            baseApiParams: {
              headers: {
                Accept: 'application/json',
              }
            }
          });
    }

    async getAuthors() : Promise<AuthorDto[]> {
        const resp = await this.tb.api.getAuthors();
        const authors = (resp).data;
        return authors;
    }

    async getOperaForAuthor(strId: string) {
        const opera = await this.tb.api.getOpera(strId);
        return opera.data;
    }

    async getAllOpera(pageNr = 0, pageSize = 20) {
      const watch = new StopWatch();      
      const resp = await this.tb.api.executeSearchTeidivGet6({ page: pageNr, size: pageSize});
      const divs = resp.data._embedded.teiDivs;
      this.log.log(`GET ${this.conf.textbaseUrl}/api/drest/teiDivs/search/findOpera?page=${pageNr}&size=${pageSize} : done, got ${divs.length} opi, took ${watch}`);
      return divs;
    }

    async getElemByPath(path: string) {
      const resp = await this.tb.api.getByPath({ path: path});
      return resp.data;
    }

    /**
     * The non-secret shared-resource naming convention (Kafka topics, the
     * Milvus collection, which embedding model) textbase-server is the
     * source of truth for -- see its AdminRestController.config(). Not part
     * of the swagger-generated client since it's a new, small endpoint;
     * plain fetch instead, same as OllamaService's calls.
     */
    async getConfig(): Promise<SharedTextbaseConfig> {
      const resp = await fetch(`${this.conf.textbaseUrl}/api/admin/config`);
      if (!resp.ok) {
        throw new Error(`GET ${this.conf.textbaseUrl}/api/admin/config failed: HTTP ${resp.status} ${await resp.text()}`);
      }
      return await resp.json() as SharedTextbaseConfig;
    }

    /**
     * @param pageSize  parameter to transmit to the api (page by page retrieval)
     * @param opId the id whose paragraphs we want
     * @param offset skip the first offset
     * @param limit  only keep limit from what remains
     */

    async *getParagraphs(opId: number, pageSize = 1000, offset = 0, limit = Number.POSITIVE_INFINITY ) {
      assert(pageSize > 0);

      var hasMore = true;
      var pageNr = Math.floor(offset / pageSize);

      let totalYielded = 0;

      while (hasMore) {

        // call /api/div/id/paras
        const watch = new StopWatch();
        
        const resp = await this.tb.api.getIdParas(opId, {
          page: pageNr,
          size: pageSize,
          withContent: 'true'
        });
        const paras = resp.data;
                
        this.log.log(`GET ${this.conf.textbaseUrl}/api/divs/${opId}/paras?page=${pageNr}&size=${pageSize}&withContent=true : done, got ${paras.length} paras, took ${watch}`);
        
        pageNr++;

        // if we got precisely the page size, maybe there's more.
        hasMore = (paras.length == pageSize);

        for (const p of paras) {

          if (totalYielded++ >= limit)
            return;

          yield p;
        }
      }        
    }

    /**
     * transforms a paged API call into a async generator
     * @param provider  the api call
     * @param pageNr    page number
     * @param pageSize  the page size
     * @param limit do not yield more than limit items
     */
    protected async *gen<T>(
      provider: (pageNr: number, pageSize: number) => Promise<Array<T>>,
      pageNr = 0, 
      pageSize = 1000, 
      limit = Number.POSITIVE_INFINITY, 
      ) :  AsyncGenerator<T, void, unknown> {
        var hasMore = true;
        let totalYielded = 0;
  
        while (hasMore) {
            
          const arr = await provider(pageNr, pageSize);
     
          pageNr++;
  
          // if we got precisely the page size, maybe there's more.
          hasMore = (arr.length == pageSize);

          for (const obj of arr) {
  
            if (totalYielded++ >= limit)
              return;
  
            yield obj;
          }
        }
    }

    allOperaGen(pageNr = 0, pageSize = 1000, limit = Number.POSITIVE_INFINITY ) {

      return this.gen<EntityModelTeiDiv>((pageNr, pageSize) => {
        return this.getAllOpera(pageNr, pageSize);
      })

  }

}