import { Injectable } from "@nestjs/common";
import { Api, AuthorDto } from "../textbase.api";

/**
 * wrapper over the api generated by swagger-typescript-api
 */
@Injectable()
export class TextbaseClient {
    protected tb: Api<string>;

    constructor() {
        this.tb = new Api({
            // baseUrl: 'http://localhost:8080',
            baseUrl: 'http://textbase.scriptorium.ro',
            baseApiParams: {
              headers: {
                Accept: 'application/json',
              }
            }
          });
    }

    async getAuthors() : Promise<AuthorDto[]> {
        const resp = await this.tb.api.getAuthors();
        const authors = (resp).data;
        return authors;
    }

    async getOperaForAuthor(strId: string) {
        const opera = await this.tb.api.getOpera(strId);
        return opera.data;
    }

    async getAllOpera(pageNr = 0, pageSize = 20) {
      const resp = await this.tb.api.executeSearchTeidivGet6({ page: pageNr, size: pageSize});
      return resp.data._embedded.teiDivs;
    }

    async *getParagraphs(opId: number, pageSize = 2000) {
      
      var hasMore = true;
      var pageNr = 0;

      while (hasMore) {

        // call /api/div/id/paras
        const resp = await this.tb.api.getIdParas(opId, {
          page: pageNr++,
          size: pageSize,
          withContent: 'true'
        });

        const paras = resp.data

        hasMore = (paras.length == pageSize);

        for (const p of paras) {
          yield p;
        }
      }        
    }
}