import { CreateIndexParam, DataType, LoadState, MilvusClient, MutationResult, RowData } from '@zilliz/milvus2-sdk-node';
import { assert, log } from 'console';
import { VectorizerConfiguration } from 'src/configuration';
import { Content } from 'src/model/model';

export class MilvusCollection {

    public milvus : MilvusClient;

    static readonly EMBEDDING = 'embedding';
    static readonly SHA256 = 'sha256';
    static readonly URL: string = 'url';

    static readonly DIM_384 = 384;
    static readonly DIM_768 = 768;
    static readonly DIM_1024 = 1024;
    static readonly DIM_2560 = 2560;

    static readonly FIELD_DESCRIPTIONS: Readonly<Record<string, string>> = {
      [MilvusCollection.SHA256]: 'Primary key: lowercase SHA-256 hex digest of the source paragraph text. Used to deduplicate unchanged text across imports.',
      [MilvusCollection.URL]: 'Canonical Textbase API URL identifying the source paragraph. Use it to retrieve the text and its document context.',
      [MilvusCollection.EMBEDDING]: 'Dense semantic vector generated by the encoder documented in this collection description. Query vectors must use that same encoder and dimension.',
    };

    constructor(
      public name: string,
      protected conf: VectorizerConfiguration,
      protected vectorDim: number = MilvusCollection.DIM_384,
      // Should identify the encoder this collection's vectors come from -
      // where it runs and its name/characteristics - since a collection is
      // only ever compatible with the one encoder it was created for. See
      // app.module.ts's MilvusCollection factory for how this gets built
      // from the real embedder in use.
      protected description: string = `embeddings storage, collection ${name}`) {
        this.milvus = new MilvusClient({
            logLevel:  'info',
            address: conf.miniMilvus,
          });
    }

    /**
     * @param vectorDim 
     *  384 is the dim for all_mini model embeddings dim
     *  768 is the dim for the all_mpnet
     */
    async create() {
      
        return await this.milvus.createCollection({collection_name: this.name,
            consistency_level: 'Eventually',
            description: this.description,

            fields: [
                {
                  name: MilvusCollection.SHA256,
                  description: MilvusCollection.FIELD_DESCRIPTIONS[MilvusCollection.SHA256],
                  data_type: DataType.VarChar,
                  is_primary_key: true,
                  autoID: false,
                  max_length: 64,
                },
                {
                  name: MilvusCollection.URL,
                  description: MilvusCollection.FIELD_DESCRIPTIONS[MilvusCollection.URL],
                  data_type: DataType.VarChar,
                  max_length: 2500
                },
                
                {
                  name: MilvusCollection.EMBEDDING,
                  description: MilvusCollection.FIELD_DESCRIPTIONS[MilvusCollection.EMBEDDING],
                  data_type: DataType.FloatVector,
                  dim: this.vectorDim,
                },
              ],
            });
    }

    async unload() {
      return await this.milvus.releaseCollection({ collection_name: this.name });
    }
    
    async drop() {
      await this.unload();
      return await this.milvus.dropCollection({
        collection_name: this.name
      });
    }

    close() {
      return this.milvus.closeConnection();
    }

    async insert(content: Content[]) {
      const data: RowData[] = content.map(it => { return {
        sha256: it.sha256,
        url: it.url,
        embedding: it.embedding
      }});

      return await this.milvus.insert({
        collection_name: this.name,
        data: data
      });
    }

    async upsert(content: Content[]) : Promise<MutationResult> {
      if (!content)
        return;

      const data: RowData[] = content.map(it => { return {
        sha256: it.sha256,
        url: it.url,
        embedding: it.embedding
      }});

      return await this.milvus.upsert({
        collection_name: this.name,
        data: data
      })
    }

    async count(): Promise<number> {
      return (await this.milvus.count({collection_name: this.name})).data;
    }

    async load() {
      return this.milvus.loadCollection({ 
        collection_name: this.name,
      } );
    }

    async findAll(output_fields = [MilvusCollection.SHA256]): Promise<any[]> {
      const resp = await this.milvus.query({ 
        collection_name: this.name,
        expr: `${MilvusCollection.SHA256} like '%'`,
        output_fields: output_fields
      });
      return resp.data;
  }

    async findById(ids: string[], outputFields = [ MilvusCollection.SHA256 ]) : Promise<Partial<Content>[]> {
      const idListAsTxt = ids.map(it => `'${it}'`).join(",");
      const expr = `${MilvusCollection.SHA256} in [ ${idListAsTxt} ] `
      const resp = await this.milvus.query({ 
        collection_name: this.name,
        expr: expr,
        output_fields: outputFields
      })

      const content: Partial<Content>[] = resp.data.map(it => { 
        const res: Partial<Content> = {};
        Object.assign(res, it);        
        return res;
      });

      return content;
    }

    /**
     * only upserts records that either do not exist at all (sha256 not present as id in 
     * the milvus collection), or whose url has changed.
     * Basically will filter out content from param whose sha256 AND url already exist in the db.
     */
    async upsertNewOrModified(content: Content[]) {
      assert(content != null);
      
      const newOrModified = await this.newOrModified(content);
      if (newOrModified.length != content.length) {
        log(`will only upsert ${newOrModified.length} new or modified out of ${content.length} total`);
      }
      return this.upsert(newOrModified);
    }

    async newOrModified(content: Content[]) : Promise<Content[]> {
      assert(content != null);
      const alreadyExisting = await this.findById(
        content.map(it => it.sha256), 
        [MilvusCollection.SHA256, MilvusCollection.URL]);
      const alreadyExistingIds = alreadyExisting.map(it => it.sha256);

      const newOrModified = content.filter(c => {
        const id = c.sha256;
        const url = c.url;
        assert (id != null);
        assert (url != null);

        const indexOfSha = alreadyExistingIds.indexOf(id);
        if (indexOfSha < 0)
          return true; // id not found so this is entirely new

        const extant = alreadyExisting[indexOfSha];
        assert (extant.sha256 != null);
        return (url != extant.url); // if urls do not match, this is modified
      });
      return newOrModified;
    }

    async createIndex() {
      await this.milvus.createIndex({
        collection_name: this.name,
        index_name:'index',
        field_name: MilvusCollection.EMBEDDING,
        extra_params: MilvusCollection.idx_ivfsq8_l2_256(),
      });
    }

  protected static idx_ivfsq8_l2_256() : CreateIndexParam {
    return {
      "index_type": "IVF_SQ8",
      "metric_type": "L2",
      "params": '{"nlist": "256"}'
    };
  }

  async getCollectionStatistics() {
      return this.milvus.getCollectionStatistics({ collection_name:  this.name })
  }

  async flush() {
    return await this.milvus.flush({collection_names: [this.name]})
  }

  async exists() {
    const resp = await this.milvus.hasCollection({
      collection_name: this.name,
    });
    return resp.value;
  }

  /** The description this collection was actually created with in Milvus (see create()). */
  async getDescription(): Promise<string> {
    const resp = await this.milvus.describeCollection({ collection_name: this.name });
    return resp.schema.description;
  }

  /** Field comments persisted in the actual Milvus schema. */
  async getFieldDescriptions(): Promise<Record<string, string>> {
    const resp = await this.milvus.describeCollection({ collection_name: this.name });
    return Object.fromEntries(resp.schema.fields.map(field => [field.name, field.description ?? '']));
  }

  /** The EMBEDDING field's actual vector dimension in Milvus (see assertVectorDimensionMatches). */
  async getVectorDimension(): Promise<number> {
    const resp = await this.milvus.describeCollection({ collection_name: this.name });
    const field = resp.schema.fields.find(f => f.name === MilvusCollection.EMBEDDING);
    if (!field) throw new Error(`Collection '${this.name}' has no '${MilvusCollection.EMBEDDING}' field`);
    const dimParam = field.type_params.find(p => p.key === 'dim');
    if (!dimParam) throw new Error(`Collection '${this.name}' embedding field has no 'dim' type param`);
    return Number(dimParam.value);
  }

  /**
   * Throws if this (already-existing) collection's actual vector dimension
   * doesn't match the dimension the currently-configured embedder produces -
   * a stale/mismatched collection (e.g. left over from a previous embedder,
   * or a config typo) would otherwise fail confusingly at the first
   * insert/search instead of loudly at startup. See app.module.ts's
   * MilvusCollection factory, which calls this right after
   * createAndLoadIfNotExists() - a freshly-created collection is always
   * self-consistent (create() uses the same vectorDim), so this only ever
   * catches a genuine pre-existing mismatch.
   */
  async assertVectorDimensionMatches(expectedDim: number): Promise<void> {
    const actualDim = await this.getVectorDimension();
    if (actualDim !== expectedDim) {
      throw new Error(
        `Milvus collection '${this.name}' has vector dimension ${actualDim}, but the configured `
        + `embedder produces ${expectedDim}-dimensional vectors - refusing to start against a `
        + `mismatched collection (wrong collection name for this embedder, or a stale collection `
        + `left over from a previous one).`
      );
    }
  }

  async createIfNotExists() {
        // if not created, create
        if (! await this.exists()) {
          await this.create();
          await this.createIndex();
        }
  }

  async createAndLoadIfNotExists() {
    await this.createIfNotExists();

    // if not loaded, load
    const state = await this.milvus.getLoadState({collection_name: this.name});
    if (state.state == LoadState.LoadStateNotLoad || state.state == LoadState.LoadStateNotExist) {
      return await this.load();
    }
    
  }

  async compact() {
    return await this.milvus.compact({
      collection_name: this.name
    });
  }

}
